// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClxV8JWPlSXbC7HfvAG-1LtKHRmcc5mP0',
    appId: '1:168419509102:web:3437220af1cd603ff3b77f',
    messagingSenderId: '168419509102',
    projectId: 'flikka-9e3f4',
    authDomain: 'flikka-9e3f4.firebaseapp.com',
    storageBucket: 'flikka-9e3f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNMT5M1Zx2jtJptLiXK7eTTExAkwmrJqc',
    appId: '1:168419509102:android:a03564e73a5289e8f3b77f',
    messagingSenderId: '168419509102',
    projectId: 'flikka-9e3f4',
    storageBucket: 'flikka-9e3f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfYQO6Ri17FhKoowl0ecVRm8AcsPb-bvc',
    appId: '1:168419509102:ios:1ae34c864d192380f3b77f',
    messagingSenderId: '168419509102',
    projectId: 'flikka-9e3f4',
    storageBucket: 'flikka-9e3f4.firebasestorage.app',
    iosBundleId: 'com.example.flikka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfYQO6Ri17FhKoowl0ecVRm8AcsPb-bvc',
    appId: '1:168419509102:ios:1ae34c864d192380f3b77f',
    messagingSenderId: '168419509102',
    projectId: 'flikka-9e3f4',
    storageBucket: 'flikka-9e3f4.firebasestorage.app',
    iosBundleId: 'com.example.flikka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClxV8JWPlSXbC7HfvAG-1LtKHRmcc5mP0',
    appId: '1:168419509102:web:39acf3c685517238f3b77f',
    messagingSenderId: '168419509102',
    projectId: 'flikka-9e3f4',
    authDomain: 'flikka-9e3f4.firebaseapp.com',
    storageBucket: 'flikka-9e3f4.firebasestorage.app',
  );
}
